### ISSUE TITLE
Matrix index out of bounds when using convex decomposition 2d

### ISSUE THREAD

**Issue by hakolao** [dimforge/parry#190]
Pretty sure this should not happen

```
thread '<unnamed>' panicked at .cargo\git\checkouts\parry-cfbedab32ac7a479\255a02f\crates\parry2d\../../src\query\clip\clip_aabb_line.rs:141:19:
Matrix index out of bounds.
stack backtrace:
   0: std::panicking::begin_panic<ref$<str$> >
             at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6\library\std\src\panicking.rs:686
   1: nalgebra::base::ops::impl$3::index_mut
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\nalgebra-0.32.5\src\base\ops.rs:66
   2: nalgebra::base::ops::impl$2::index_mut
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\nalgebra-0.32.5\src\base\ops.rs:58
   3: parry2d::query::clip::clip_aabb_line::clip_aabb_line
             at .cargo\git\checkouts\parry-cfbedab32ac7a479\255a02f\src\query\clip\clip_aabb_line.rs:141
   4: parry2d::transformation::voxelization::voxel_set::VoxelSet::compute_exact_convex_hull
             at .cargo\git\checkouts\parry-cfbedab32ac7a479\255a02f\src\transformation\voxelization\voxel_set.rs:200

```

**Comment by dylanowen** [comment]
I was running into the same stack trace and I believe it ultimately was caused by: https://github.com/dimforge/rapier/pull/660
