### ISSUE TITLE
panicked at epa3.rs

### ISSUE THREAD

**Issue by rustui** [dimforge/parry#202]
```
thread '<unnamed>' panicked at parry3d-0.13.7/src/query/epa/epa3.rs:129:13:
assertion left == right failed
left: 9
right: 8

Encountered a panic in system `bevy_rapier3d::plugin::systems::step_simulation<()>`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
thread 'main' panicked at winit-0.29.15/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```
I have run my game hundreds of times, and this is the first time it crashed due to this. Because it's so rare, I don't know how to reproduce it, and subsequent runs of the game haven't encountered this issue again.
It's possible that it has already been fixed since I'm not using the latest version. So, I'm just noting it here for now.

**Comment by rustui** [comment]
I encountered this panic in the latest version 0.15.1 as well, but only once so far.
```
thread '<unnamed>' panicked at src/query/epa/epa3.rs:129:13:
assertion left == right failed
left: 9
right: 1
```

**Comment by sebcrozet** [comment]
I removed the panic in favor of a debug log, so that this corner case doesn’t crash the whole app until we get around to debugging it.
